### ISSUE TITLE
Arnav(Contributed 3 projects) 

### ISSUE THREAD

**Issue by arnav108276** [Build-In-Bharat/FrontendWonders#10]
## Frontend Wonder Description

[Provide a brief, engaging description of your Frontend Wonder. What makes it unique or interesting?]

## Type of Submission

- [ ] CodePen Link / Github Link / (or any other static site link with repo URL)
- [ :white_check_mark:] New Folder in Repository

## Implementation Details

[For CodePen submissions, include your CodePen link here]
[For new folder submissions, describe the files you'll be adding and any special instructions for viewing]

## Technologies Used

- [:white_check_mark: ] HTML
- [:white_check_mark: ] CSS
- [:white_check_mark: ] JavaScript
- [ :white_check_mark:] OpenGL
- [:white_check_mark:] Python
- [:white_check_mark:] Batch file
- [:white_check_mark:] MongoDB
- [:white_check_mark:] C

## Preview

![image](https://github.com/user-attachments/assets/55e3ec44-eeb4-4975-bc9b-763c7df4dd2f)

## Inspiration
It was shared in one our official groups at my university to encourage students.The initiative encouraged me to explore and implement new features, combining practical skills with creativity to build a Node.js-powered website. The collaborative spirit of the university environment pushed me to develop this project and contribute to the open-source community.

## Feedback Requested
As a contributor to the [Build-In-Bharat/FrontendWonders](https://github.com/Build-In-Bharat/FrontendWonders.git) project, I would appreciate any feedback on my submission. I’m particularly interested in suggestions for improving code structure, design, and user experience. Please feel free to share any ideas for new features or report any bugs you encounter. Your feedback will help me grow and contribute more effectively to this community project!

## Checklist

- [:white_check_mark: ] I have read the CONTRIBUTING.md file
- [:white_check_mark: ] My submission is my original work
- [:white_check_mark: ] I have tested my Frontend Wonder in multiple browsers (if applicable)
- [ ] I have commented my code for better understanding (if applicable)
- [✅ ] I am ready to submit a Pull Request

**Comment by MohakBajaj** [comment]
Stale. Closing
